version: "3.9"

services:
  db:
    image: postgres:16
    container_name: equityflow_db
    environment:
      POSTGRES_USER: equityflow
      POSTGRES_PASSWORD: equityflow_pass
      POSTGRES_DB: equityflow
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U equityflow -d equityflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: equityflow_backend
    env_file:
      - ./backend/app/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    container_name: equityflow_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
